### ISSUE TITLE
Angular.js compatibility

### ISSUE THREAD

**Issue by gmarciani** [sbilly/joli-admin#2]
Hi @sbilly , thank you for your great work!
I am developing an angular web app that leverages Joli as template. 
I see that some important Bootstrap features are broken when encapsulating the HTML inside (i) a directive or (ii) an ng-include or (iii) ng-if. 

For instance, when encapsulating the top-bar or the nav-bar inside an ng-if, the toggle feature is broken.
Futhermore, when encapsulating a table or a modal inside a ng-include, nothing seems to work.

I think it would be caused by some incompatibility between the jQuery inside Bootstrap and the jQLite inside Angular.

What kind of solution do you suggest?

**Comment by sbilly** [comment]
I just forked from http://themifycloud.com/downloads/freee-responsive-bootstrap-joli-angular-js-admin-template-dashboard-web-app/.

You can contact the original author for help.

**Comment by darkmakukudo** [comment]
@sbilly  @gmarciani 
the problem here is the events are listened using jquery and the events are not reachable because the elements or objects in DOM were not yet loaded. 

So for the events to work (e.g. logout modal) you need to alter the jquery scripts to listen events when the element is loaded like this : 

$(document).on("click", ".mb-control", function () {

I hope someone can fork a clean angular js version of this project.
Looking forward to it.

**Comment by sbilly** [comment]
You can send a PR, if you solved this problem

**Comment by Dineshrajaa** [comment]
I am also facing the same issue.. did you get any solution for this @gmarciani ?

**Comment by juanto** [comment]
Anyone could fix it?
Im facing the same problem too.

**Comment by darkmakukudo** [comment]
@juanto  @Dineshrajaa  look at my comment above, that's how I fixed the problem.

**Comment by juanto** [comment]
@cariquitanmac yes that worked for me.
Thanks
